# https://hub.docker.com/_/mongo
version: "3.1"

services:
  mongo:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: g11n-services-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: main
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
